### ISSUE TITLE
After upgrading expo to 50 and react native to 0.73,  get an error

### ISSUE THREAD

**Issue by master429** [achorein/expo-share-intent-demo#29]
**Describe the bug**
When I upgraded expo to 50 and react native to 0.73, after running yarn and prebuild, I got an error when running pod install in the ios directory

**To Reproduce**
upgraded expo to 50 and react native to 0.73, after running yarn and prebuild

** Environment **
System:
  OS: macOS 13.4
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 36.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**Additional context**
- expo version (ex: 50)
- branch (ex: expo49-expo-router)
- target : iOS
- device : real device
- type: local build

**Comment by master429** [comment]
![Uploading 截屏2024-01-26 14.29.41.png…]()

**Comment by master429** [comment]
<img width="1112" alt="截屏2024-01-26 14 29 41" src="https://github.com/achorein/expo-share-intent-demo/assets/76980858/e6f798e4-0dfa-4b30-bbf0-c141ad305214">

**Comment by master429** [comment]
@achorein Can you help me solve this problem?

**Comment by wodin** [comment]
The "string-width" thing was addressed here:
https://github.com/expo/expo/pull/26459

Try running `npx expo install --fix`

**Comment by master429** [comment]
> The "string-width" thing was addressed here: [expo/expo#26459](https://github.com/expo/expo/pull/26459)
> 
> Try running `npx expo install --fix`

I have run this command, but still get the same error
<img width="912" alt="截屏2024-01-26 15 50 03" src="https://github.com/achorein/expo-share-intent-demo/assets/76980858/b3153025-ffdf-464c-b8c4-16e7a9ca65bc">

**Comment by master429** [comment]
> The "string-width" thing was addressed here:“string-width”问题在这里得到解决： [expo/expo#26459 世博会/世博会#26459](https://github.com/expo/expo/pull/26459)
> 
> Try running `npx expo install --fix` 尝试跑步 `npx expo install --fix`

I updated yarn from v1 to v4 and this error was resolved. Thank you very much for your help

**Comment by master429** [comment]
> i didn't test with expo 50 as is still in beta. I will a add a demo branch when it get ready.我没有在 Expo 50 上进行测试，因为目前仍处于测试阶段。当它准备好时，我将添加一个演示分支。
> 
> otherwise, after the `yarn test:fix` you should also do a `yarn clean`否则， `yarn test:fix` 在 你还应该做一个 `yarn clean`

I resolved this issue by upgrading the yarn version. Thank you for your effort

**Comment by wodin** [comment]
> i didn't test with expo 50 as is still in beta.

Expo SDK 50 was released on 2023-01-18

**Comment by zirlman** [comment]
Hey. Just wanted to say that I've upgraded my Expo project to v50 and was able to create a build. However, when trying to share a text/image into the app the share intent listeners don't get triggered. It just opens the app (Android emulator). 
Because of that I had to rollback to v49 for now. 

@achorein I hope you make it work 🙏

**Comment by troyshu** [comment]
@zirlman I'm running into the same issue, where the sharing intent listeners don't get triggered on Android (upgraded to Expo 50). Sharing with iOS seems fine.

@achorein I started working on Expo 50 support for `expo-share-intent-demo`, but got stuck on the Android issue above. Here's my draft PR for easy viewing of diffs: https://github.com/achorein/expo-share-intent-demo/pull/30. Would love to get some help debugging the Android issue. Your amazing work with this repo was the only working way to receive share intents on Expo 49, so hoping we can get it working for Expo 50! Thanks!

**Comment by achorein** [comment]
alright !
@troyshu i fixed your PR and got a working version 🎉 , i let you test on your device (don't forget the `yarn clean`)

**Comment by troyshu** [comment]
What a pleasant surprise this morning! Thank you for your quick reply and hard work @achorein . I just tested on my Android device and receiving the share intent is working again! Will continue the discussion in the PR to get it merged

**Comment by achorein** [comment]
PR #30 merged 🎉 
@master429 @zirlman You can checkout the `expo50` branch.
Feel free to reopen an issue if needed.

**Comment by zirlman** [comment]
> PR #30 merged 🎉 
> @master429 @zirlman You can checkout the `expo50` branch.
> Feel free to reopen an issue if needed.

Thank you so much 🙏! I'll test it right now and give you feedback. No matter the outcome, I really didn't expect that you'd tackle this issue so quickly. The least I could do is support your work. I hope the coffee you drink isn't more than 5€ 😅.
